addr: 0.0.0.0:8759
source_dir: /data1/home/wenjuxu/KOServer
remote_dir: c:/Users/wenjuxu/Desktop/KOServer
make_cmd_path: /usr/bin/bmake

protocol:
  source_dir: libsrc/protocol
  target_dir: build/libsrc/protocol
  build_dir: build/libsrc/protocol

oss_desc:
  source_dir: libsrc/log
  target_dir: libsrc/log
  build_dir: build/libsrc

excel:
  source_dir: excel/excel_config
  target_dir: build/excel/confgen/conf
  build_dir: build/excel
